---
- hosts: all 

  vars:

    copr_repos: 
    - rmonk/signal

    extra_repos:
    - name: "fedora-spotify-negativo17"
      description: "negativo17 - Spotify"
      baseurl: https://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
      enabled: no
      gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
      gpgcheck: yes 

    packages: 
    - package: git
    - package: terminator
    - package: vim
    - package: hexchat
    - package: linphone
    - package: gnome-shell-extension-panel-osd.noarch
    - package: gnome-tweak-tool
    - package: docker
    - package: signal-desktop  ## Uses rmonk/signal (copr repo)
    - package: firefox
    - package: wireshark
    - package: meld
    - package: meld
    - package: audacious
    - package: spotify-client
      repo: fedora-spotify-negativo17

  roles:
  - role: copr_repos
  - role: packages
