---
- hosts: 127.0.0.1

  vars:

    extra_repos:
    - name: "fedora-spotify-negativo17"
      description: "negativo17 - Spotify"
      baseurl: https://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
      enabled: no
      gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
      gpgcheck: yes 

    packages: 
    - package: git
    - package: terminator
    - package: vim
    - package: hexchat
    - package: linphone
    - package: gnome-shell-extension-panel-osd.noarch
    - package: gnome-tweak-tool
    - package: docker
    - package: firefox
    - package: wireshark
    - package: meld
    - package: meld
    - package: audacious
    - package: spotify-client
    - package: policycoreutils
    - package: policycoreutils-python 
    - package: selinux-policy 
    - package: selinux-policy-targeted 
    - package: libselinux-utils 
    - package: setroubleshoot-server 
    - package: setools 
    - package: setools-console 
    - package: mcstrans

  roles:
  - role: packages
